version: '3'

services:
  mongodb:
    image: "mongo"
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
  server:
    build: ./server
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm run start:dev
  client:
    build: ./client/
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/:/usr/src/app/client:rw
      - /usr/src/app/client/node_modules
    links:
      - server
    command: npm run start