version: '3'

services:
  mongodb:
    image: "mongo"
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/usr/src/app/server
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm run start:dev
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/:/usr/src/app/client
    links:
      - server
    command: npm run start